services:
 - docker
 - conda
before_script:
 - sudo apt-add-repository ppa:swi-prolog/devel -y
 - sudo apt-get update -q
 - sudo apt-get install swi-prolog-nox
 - sudo apt-get install curl
# - git curl source <(curl -s https://raw.githubusercontent.com/TeamSPoon/PrologMUD/master/pack/prologmud/runtime/web_install.sh)
 - sudo apt-get install openjdk-8-jdk
 - sudo apt-get install python3.6
 - sudo apt-get install sbcl
 
script:
# - swipl -g "pack_install(logicmoo_utils),halt" -t 'halt(1)'
# - swipl -s t/test_no_repeats.plt -g run_tests,halt -t 'halt(1)'
conda install -c conda-forge jupyterlab

 curl install -o /tmp/ql.lisp http://beta.quicklisp.org/quicklisp.lisp
$ sbcl --no-sysinit --no-userinit --load /tmp/ql.lisp \
       --eval '(quicklisp-quickstart:install :path "~/.quicklisp")' \
       --eval '(ql:add-to-init-file)' \
       --quit
# - docker build -t moo-test .
# - docker run moo-test npm run test
